# Generated by Django 4.2.4 on 2023-08-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfEvent', models.CharField(max_length=99)),
                ('socialMediaLinks', models.URLField()),
                ('name', models.CharField(max_length=99)),
                ('phoneNumber', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=254)),
                ('dateOfEvent', models.DateField()),
                ('city', models.CharField(max_length=99)),
                ('countOfClasses', models.IntegerField()),
                ('countOfWinners', models.IntegerField()),
                ('fileOfRules', models.FileField(upload_to='')),
                ('deliveryAddress', models.CharField(max_length=99)),
                ('comment', models.CharField(max_length=999)),
            ],
        ),
    ]
