# Generated by Django 4.2.4 on 2023-08-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='countOfClasses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='countOfWinners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dateOfEvent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='deliveryAddress',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='fileOfRules',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
