# Generated by Django 4.2.4 on 2023-08-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_application_fileofrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='dateOfEvent',
        ),
    ]
