# Generated by Django 4.2.4 on 2023-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_application_dateofevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dateOfEvent',
            field=models.DateField(null=True),
        ),
    ]
