# Generated by Django 4.2.4 on 2023-08-16 06:56

import app1.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_application_dateofevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fileOfRules',
            field=app1.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
